language: java
services:
  - docker
before_install:
  - docker pull fsfe/reuse:latest
  - docker run --name reuse -v ${TRAVIS_BUILD_DIR}:/repo fsfe/reuse /bin/sh -c "cd /repo; reuse lint"
jdk:
  - openjdk8
  - openjdk9
  - openjdk10
  - openjdk11
  - openjdk12
  - openjdk13
addons:
  apt:
    packages:
    - xvfb
    - vnc-java
    - x11vnc
    - tightvncserver
env:
  - DSPLAY=:0
before_script:
  - pip install --user codecov

after_success:
  - codecov
